language: generic 
sudo: required

services:
  - docker

before_install:
  - docker build -t altamashali/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true altamashali/docker-react npm run test
